### ISSUE TITLE
Second controller (PS5) won't connect in windows version

### ISSUE THREAD

**Issue by BrenhamH** [WinterSquire/AlphaRing#13]
My xbox controller connected fine as controller 1, but the second controller was unresponsive to all other 3 input options. Game froze when 'controller 1' was assigned to second player. Windows and steam (in the background) recognized the second controller just fine.

**Comment by WinterSquire** [comment]
Did you enable Steam Input for MCC?

**Comment by BrenhamH** [comment]
I’m not running it through steam. Is that required?

**Comment by WinterSquire** [comment]
Or you need to have software that can convert your PS5 controller input into Xbox input, as the game only receives XInput.
