### ISSUE TITLE
[Question] Does this mod work by implementing an unused feature in MCC?

### ISSUE THREAD

**Issue by kylepitcock** [WinterSquire/AlphaRing#18]
Like is this using a feature that was never used or could someone else theoretically use this same implementation to a game such as left 4 dead or one of the older call of duty games?

**Comment by WinterSquire** [comment]
The splitscreen function is already built into the game.
What I [did](https://github.com/WinterSquire/AlphaRing/blob/4e098bc076ed66af2ee3c59a380c270301603a62/src/hook/mcc/mcc.cpp#L44) was detour the get local player function and make the game think you have more than one local player.
You can't apply this method to other games.
I might write a wiki page explaining this in detail someday.
