### ISSUE TITLE
Feature request: Different sound sources for different players

### ISSUE THREAD

**Issue by DaRkPaToU** [WinterSquire/AlphaRing#21]
I'm guessing this is unlikely to be possible but I would love if each split screen player could choose a different sound source than "Player 1".

**Comment by WinterSquire** [comment]
sound impossible

**Comment by WinterSquire** [comment]
Thank you for the request. Implementing this is nearly impossible.
Also, the game's sound should not only come from Player 1; it should be a mix of all players' sounds, right?

**Comment by WinterSquire** [comment]
You can use this mod within Nucleus Coop.
This way you will get two different sound sources.

**Comment by DaRkPaToU** [comment]
I keep getting this error while trying to run it via Nucleus Coop... This happens after about 5 seconds after the game is loaded
![Capture d'écran 2024-06-10 131814](https://github.com/WinterSquire/AlphaRing/assets/80935237/65691c63-aa92-4a51-820c-350d8660886e)
