### ISSUE TITLE
incorrect zoom with modded weapons on CE.

### ISSUE THREAD

**Issue by Sir-LoLz** [WinterSquire/AlphaRing#27]
when you zoom in with a modded weapon the screen shrinks by half. 

https://youtu.be/slMFH1Eb5lU

map used https://steamcommunity.com/sharedfiles/filedetails/?id=2898867177&searchtext=lava+lab

**Comment by WinterSquire** [comment]
This is more likely a problem relates to the HUD interface tag of the modded weapon.
Please contact the map creator to fix it.
