### ISSUE TITLE
H2A splitscreen broken

### ISSUE THREAD

**Issue by geomusicmaker** [WinterSquire/AlphaRing#29]
Hi,

Firstly, thank you for making this mod. You have no idea how happy I was to find it and make the possibility of playing with my partner possible. Why they didn't include this in the official release when all of the capability is there is insane.

Anyway... for the most part this mod is working flawlessly for me. However, I've found that H2A doesn't work as expected. See below:
![h2a broken 2](https://github.com/WinterSquire/AlphaRing/assets/173182127/19372526-b3b6-4d2f-aa62-c43d6f2689ca)

But if I hit TAB to go back to classic, it works fine.
![H2c normal 2](https://github.com/WinterSquire/AlphaRing/assets/173182127/9f4d9d7a-be5d-458b-99f1-42c711244ec6)

It looks like player 2's camera is being stretched across the entire screen as the HUD for both players is still correct and present. I see a similar issue has been raised by someone on a steamdeck but this is on PC. Is this a known bug or am I finding something new?

**Comment by Nethseaar** [comment]
Same experience for me. 2-player works fine using the mod, but 3- or 4- player puts player 1's view into fullscreen with the separator lines and HUDs of the other players over the top.

Going into classic fixed it for players 1-3, but player 4's screen was black.


![20240629185247_1](https://github.com/WinterSquire/AlphaRing/assets/4545126/8f9c3450-9b13-487e-b293-f93932d329d4)
![20240629221609_1](https://github.com/WinterSquire/AlphaRing/assets/4545126/8adf8ea5-de40-4f60-bc53-a7eb428326c8)

**Comment by Jack-Culcasi** [comment]
For me H2A (MCC, Steam, PC) works perfect but the cinematics are not centred on the screen

**Comment by WinterSquire** [comment]
According to my research, the splitscreen code for anniversary graphic is hard-coded to 2 players. So this issue is probably not gonna be solved.

**Comment by geomusicmaker** [comment]
> According to my research, the splitscreen code for anniversary graphic is hard-coded to 2 players. So this issue is probably not gonna be solved.

I'm not trying to get more than two players though. It is only one players camera stretched across the two split screen panels which isn't right.

**Comment by WinterSquire** [comment]
Oh sorry, I didn't notice that. Normally 3/4 splitscreen players would cause that.
I just pushed a new commit trying to fix that. Can you test the dev [build](https://ci.appveyor.com/project/WinterSquire/alpharing/build/artifacts) to see if that works?

**Comment by Dragneel276** [comment]
Dev Build seems to work for me, H2A now properly scales across in 2 player co-op (at least in my brief testing)
![Screenshot 2024-07-26 230201](https://github.com/user-attachments/assets/4c2ccd1f-9f3e-42fb-8d81-7741d66c0ac2)


also the scoring hud is kinda wack, not sure if that's even a fixable bug at this point (probably not too important yet)


Curiously, the original issue is still kinda prevalent in 4 player co-op, as 2 POVs are now being stretched, instead of only one.
![Screenshot 2024-07-26 230708](https://github.com/user-attachments/assets/6bb5559a-6716-4fc6-8587-aa3493726890)
^^ Halo 2, working fine? (this is so cool dude)


![Screenshot 2024-07-26 230658](https://github.com/user-attachments/assets/f0a81ceb-96b4-4b39-8090-791b832fdeee)
^^ H2A working less fine, with a lot of texture pop-in. (among other issues lol)

**Comment by geomusicmaker** [comment]
OK, so this new build has fixed the initial problem of one player's camera being stretched across two. However, there are now control issues. 

For context, Player 1 is using K/M and Player 2 using controller testing on Outskirts. 

All is fine until Player 2 shoots using controller. From that point, Player 1's fire controls on the mouse go dead and only comeback by disabling the mod, shooting, and then re-enabling, but as soon as Player 2 shoots again, it reverts to broken. I can create a separate issue for this if it helps?

**Comment by WinterSquire** [comment]
[fixed](https://github.com/WinterSquire/AlphaRing/commit/87173ffc3f01c6fb7f6e9174ab000b7d11d54e9f)

**Comment by WinterSquire** [comment]
No problem, if you don't have any other questions with this issue, please close it. ☺️

**Comment by rabidrivas** [comment]
Is there any reason why this fixes havent been added to the release yet?
