### ISSUE TITLE
Lighting glitches in halo reach splitscreen

### ISSUE THREAD

**Issue by Auonghada** [WinterSquire/AlphaRing#30]
In halo reach multiplayer (haven't tested campaign), there's lots of lighting issues, on the first person player model, weapon model and especially when zoomed in.
![image](https://github.com/WinterSquire/AlphaRing/assets/103259194/a9982a71-b8fa-4c86-bee7-106380a2101b)
![image](https://github.com/WinterSquire/AlphaRing/assets/103259194/5416164c-1192-4774-b8ea-5e6f0c1d717b)

These issues occur only when using splitscreen.
My system is running Arch Linux, using Intel UHD 620 graphics and Proton 9.0-2.

**Comment by Auonghada** [comment]
After further testing it looks like these glitches only happen when the game is running at a resolution lower than 1366x768

**Comment by tfarrprogramming** [comment]
I've also had the same issue, I wonder what is causing it.
