### ISSUE TITLE
Please help, Cannot change teams

### ISSUE THREAD

**Issue by Skinny-Meat** [WinterSquire/AlphaRing#36]
When playing multiplayer "pvp" I'm having an issue where if anyone on either PC (2x PC LAN) trys to swap teams from red to blue or visa versa the game locks up on the PC where the team switch was attempted.

Is there a work around or is this a know. Issue?

Thanks

**Comment by WinterSquire** [comment]
[duplicate](https://github.com/WinterSquire/AlphaRing/issues/32#issue-2362927255)
