### ISSUE TITLE
Hook failed to initialize (Lutris)

### ISSUE THREAD

**Issue by pitcairnislands** [WinterSquire/AlphaRing#41]
Hi, I've been trying to get the mod to work via Lutris/Wine but it wouldn't work; the menu works and I can toggle it with F4 but nothing more, console output marks no error with the mod at least since v1.0.87 but still a message pops up with "Alpha Ring: Hook failed to initialize"

![Screenshot from 2024-07-12 16-33-47](https://github.com/user-attachments/assets/035ce6e8-d4f8-4b76-94a0-29fca9f77d98)

Any help or comments are much appreciated.

**Comment by WinterSquire** [comment]
The game version is mismatched. It should be the same as the first version. Which version of MCC did you use?

**Comment by WinterSquire** [comment]
This tool currently only work for the latest game. Please update the game.
