### ISSUE TITLE
Thank You very much 

### ISSUE THREAD

**Issue by Destroyer5150** [WinterSquire/AlphaRing#42]
Wife and I couldn't get it to work using nucleus. Thank you very much! This works perfectly. Can't wait to see how this turns out in the future. If you feel like tackling another one that should have included split screen on the PC port, we've been playing Saints Row the third using nucleus but it's far from perfect.

**Comment by WinterSquire** [comment]
No problem. I'm glad to hear this tool worked well for you.
However, I'm focusing on Halo atm, and this split-screen method is specifically designed for Halo.
So I won't make a splitscreen tool for it.
