### ISSUE TITLE
Support Split Screen Across Multiple Displays

### ISSUE THREAD

**Issue by FahadBSyed** [WinterSquire/AlphaRing#52]
This may be a strange ask. Imagine I have two monitors and I want to run splitscreen. Perhaps I want player one on monitor one and player two on monitor two. Is this currently possible. If not, is it feasible to support?

**Comment by WinterSquire** [comment]
Currently it is not possible, it might be implemented in the future, and this issue is [duplicated](https://github.com/WinterSquire/AlphaRing/issues/16).
