### ISSUE TITLE
"AlphaRing:MCC Hook Failed to Initialize"

### ISSUE THREAD

**Issue by SleepyLark** [WinterSquire/AlphaRing#7]
I'm using the Microsoft Store version and have the latest version of VS C++ as linked here. The .dll is in the right folder and I'm launching without EAC enabled. After opening there is a cmd prompt and a window saying "AlphaRing:MCC Hook Failed to Initialize". The mod appears to somewhat load as the UI bar is there, however when trying to connect controllers it doesn't appear to work in game and I can't control the mod menu with my controller (Controller Start + Controller Back works however to open it). Is there something I'm missing here or is it because I'm not using the Steam version? Is it even possible to use the MS version? This is the first time I've used mods on Halo so apologies if the answer is obvious.

**Comment by WinterSquire** [comment]
Can you include the contents of the terminal?

**Comment by SleepyLark** [comment]
Give me a sec but it was pretty much two lines that said something along the lines of starting AlphaRing and initialization failed

**Comment by SleepyLark** [comment]
> Can you include the contents of the terminal?
@WinterSquire 
[2024-06-04 22:12:14.198] [info] Version: 1.3385.0.0
[2024-06-04 22:12:14.794] [error] MCC Hook Fail To Initialize!

![Screenshot 2024-06-04 221917](https://github.com/WinterSquire/AlphaRing/assets/37351525/9b6e5ed9-1940-401d-b553-95dc8e4d3826)

Also the mouse does work on the controller for the mod menu, I was just using the wrong stick 🫠

**Comment by WinterSquire** [comment]
This happened because the executable file names for Steam and Windows Store's MCC are different, and I used the Steam version's name to locate the address.
I have already submitted a [commit](https://github.com/WinterSquire/AlphaRing/commit/2fd0107960270915943902bcd6fcf48d0df9243c) to fix, and you can try the latest [Dev Build](https://ci.appveyor.com/project/WinterSquire/alpharing/build/artifacts).

**Comment by SleepyLark** [comment]
Looks like it's now able to hook, however now it's crashing when I try to press start on the main menu

**Comment by WinterSquire** [comment]
By pressing start, did you mean pressing `F4`?

**Comment by SleepyLark** [comment]
> By pressing start, did you mean pressing `F4`?
No when I try pressing start in the game. It loads to the title screen and trys to load and then crashes regardless if the mod is turned on or not

**Comment by WinterSquire** [comment]
Can you send me a copy of the windows store version? So I can do some research with it. I was told that the windows store version is actually different from the steam version.

**Comment by SleepyLark** [comment]
Yeah just the `MCC-Win64-Shipping.exe` file? I'm away from my computer right but I can do it by the end of the day

**Comment by WinterSquire** [comment]
Yes

**Comment by SleepyLark** [comment]
@WinterSquire 
The file permission were weird when I tried to move it , but hopefully this works

https://files.catbox.moe/3jrl9v.7z

**Comment by WinterSquire** [comment]
The executable file is actually encrypted. Someone sent me the executable file before.
There is a way to bypass the encryption system. I'm going to buy a Windows Store version and see if I can bypass it.

**Comment by SleepyLark** [comment]
R.I.P. Worst case I guess I'll have to buy this again for the third time just to use the Steam version instead. Good luck with the research🙏 🙏

**Comment by WinterSquire** [comment]
This should be quick, like 3-4 hours. I just need a non-encrypted executable file. The research should be really simple.

**Comment by WinterSquire** [comment]
I submitted a [commit](https://github.com/WinterSquire/AlphaRing/commit/8816284f0029ca23d46f1f01789507f9e107f256) to fix it, you can test the build [here](https://ci.appveyor.com/project/WinterSquire/alpharing/build/artifacts).
I still need some test before releasing it to make sure it can work on Steam Deck too.

**Comment by SleepyLark** [comment]
I tested it and it seems to work almost perfectly (at least during the beginning, I haven't had time to finish a level yet). The only issue I saw is if you're using the remastered graphics for halo 1 and 2 you can only do 2 players, however using the og graphics let's you have 4 players

**Comment by WinterSquire** [comment]
Yeah, the remastered graphics are only designed for 1 or 2 players.

**Comment by SleepyLark** [comment]
Cool, am I good to close this then?

**Comment by WinterSquire** [comment]
Yeah

**Comment by SleepyLark** [comment]
Awesome, thanks again for the mod. Now I can finally play with all my siblings

**Comment by islander2020** [comment]
I'm having the same issue, did the fix make it into the latest release? I'm using it but still getting the "Hook Failed to Initialize". I wasn't sure how to use the link to the Dev build, I should compile it? Thanks I'm new to a lot of this.

**Comment by gpanous** [comment]
where do i put the build(in which file)

**Comment by AlphaOmega786** [comment]
Hi, having the same issue, using both steam ver. Of halo mcc and the most recent ver. Of the Alpharing mod. I've gotten 3 lines of text. (Which will be shown in image) practically saying the mcc Hook failed to initiate. The UI shows as normal, however it does not impliment into the game. It does not enter split screen when I enter the game. 

![Image](https://github.com/user-attachments/assets/a2084c8c-8f35-4444-a4fa-1f450d418eb9)

**Comment by MGadeau** [comment]
même problème, je vais pas remettre l'image car c'est le même message que AlphaOmega786. 
Je suis aussi sur steam

**Comment by OakenStake** [comment]
I have the same problem. I'm hoping to play.

![Image](https://github.com/user-attachments/assets/2d0ed180-2db6-41b7-9222-91bdcc407105)
