### ISSUE TITLE
Camera goes crazy for mouse and keyboard player.

### ISSUE THREAD

**Issue by SomaBenjamin** [WinterSquire/AlphaRing#8]
I tried the mod, but for some reason, the camera kept going up and left for the first player.

**Comment by WinterSquire** [comment]
Can you record a video to demonstrate this?

**Comment by SomaBenjamin** [comment]
Yes, here you go.
https://github.com/WinterSquire/AlphaRing/assets/120260371/ca5c85b7-fb71-4fe3-9d44-24e0abf7657e

**Comment by SomaBenjamin** [comment]
Ok, thank you!

**Comment by WinterSquire** [comment]
No worries

**Comment by WinterSquire** [comment]
[fixed](https://github.com/WinterSquire/AlphaRing/releases/tag/1.0.82)
