### ISSUE TITLE
Version mismatch dev build

### ISSUE THREAD

**Issue by DNA-Photo** [WinterSquire/AlphaRing#86]
hi, i cannot update the game version since it is not associated to any platform like steam or win store and with the recently uploaded dev version i keep getting this error: 
![1](https://github.com/user-attachments/assets/23729f7c-bdaa-43b8-bda1-9d079ff9d81b)
as soon as i press OK this appears and the game closes: 
![2](https://github.com/user-attachments/assets/75db1082-c2ab-4ba3-8da0-a11f85e4840a)
any suggestion?

**Comment by Fesiug** [comment]
That version of MCC looks extremely old I doubt you'll be able to use the app

**Comment by DNA-Photo** [comment]
I guess steam did the right thing on those autumn sales, so i got the last version and the mod now works flawlessly. Thank you!
