### ISSUE TITLE
Fatal Error at Game Launch on Steam Deck

### ISSUE THREAD

**Issue by bjdealey** [WinterSquire/AlphaRing#9]
When attempting to launch MCC with the mod installed, the game displays a “Fatal Error” message before crashing shortly after the main menu loads.

**Comment by WinterSquire** [comment]
This might be because of the [change](https://github.com/WinterSquire/AlphaRing/commit/2fd0107960270915943902bcd6fcf48d0df9243c) I recently made to make it work on Windows Store. I have removed that release, and the previous release should work fine on Steam Deck.

**Comment by WinterSquire** [comment]
You can test the latest Dev Build [here](https://ci.appveyor.com/project/WinterSquire/alpharing/build/artifacts).
Let me know if it works on Steam Deck.

**Comment by bjdealey** [comment]
Thank you for following up on this. I have tried the latest dev build and i’m getting the same error. I will try the other versions and see if the issue occurs.

**Comment by WinterSquire** [comment]
The latest [release](https://github.com/WinterSquire/AlphaRing/releases/tag/1.0.69) should fix it.
It seems there is something wrong with the Build System.

**Comment by WinterSquire** [comment]
I investigated further and discovered that this issue was caused by a mismatch between the MSVC version used in the Steam Deck environment and the one used in the build system. I have now downgraded the compiler version in the build system, and the problem is resolved.
